import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { onnxRedirectPlugin } from './esbuild-plugin-onnx-patch.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  define: {
    // CRITICAL: This fixes transformers.js environment detection in Obsidian
    // transformers.js checks: process?.release?.name === 'node'
    // In Obsidian's Electron renderer, process.release.name returns 'node'
    // Setting it to undefined makes transformers.js use browser mode instead
    // This prevents it from trying to load Node.js-specific ONNX runtime
    'process.release': 'undefined',
  },
  plugins: [onnxRedirectPlugin], // Additional safety: redirects onnxruntime-node to onnxruntime-web
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
